language: go
os:
- linux
go:
- 1.14.x
script: "./build.sh"
matrix:
  allow_failures:
  - go: tip
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: build/blaster
  on:
    tags: true
