language: go
os:
- linux
go:
- 1.14.x
script: "./build.sh"
matrix:
  allow_failures:
  - go: tip
deploy:
  provider: releases
  api_key:
    secure: Qzq1B98nUNJ+6gqxNzNx8ekHV72msPECM2lNERemckpdabLUMQl29bvrxeWWmz0oflDL7FIGjOEU0VmORU5a4Gm1rZWMV6SmHZZVOGxtT1cOC/znGa36WIVwG9uXW3m9DYX8e97VtrzOdPSV0TJga571rngIdl3pFCjz3rY6Fl2PIkJg5J3orUawIX3afqTYlgwSbtCmbLxtJ7o69um2psxTJebOu9YG1+bMX9yKV2fdW1JGgclCQ96n4CQ9vDrU+BV0o2RNKZAlMHTQt8BKaHidJEpFXZBy0BxlnP9Y0sC3NPzduDcEDCSKF/zYrRbkJJdQ6Eksz6UebL7WtxHSLJ3SXl5rkIsQg9W9R8jSAJCTN3PxQJLWGb1U/ecLCqR0jqTTnLY2tBON/q76p2arnj7YmfvSqz4pJ1v2V/QVqLl2DF/3mZRhNlRovwRTrkvuWv959N086Nradm46/qmYqAcJVQ4Vn8q0hqba1unSRuFlxqk8uf67gXYaqGYhI+9RdnEmJbsE0P4CZjEL9tr3b3V4iYZcm82A4wXgtpKeaqCycY830P6EZg9zz0mkbv7jbk598iqsbAhYUDOFQSbrUvXjoEjvZQWQj5I5MAMeXmMG93Rt6+Vr++eEZfMZnYYZsdSJPBi5vwcwayDvex975+xjaXkt0WXbIhEvNYVKcTg=
  skip_cleanup: true
  file: build/blaster
  on:
    tags: true
    repo: buddyspike/blaster
